## Imports

In [1]:
import pandas as pd

In [2]:
df_global = pd.DataFrame

In [3]:
df_global = pd.read_csv("../../data/france/france_clean.csv")

In [4]:
df_global.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8314 entries, 0 to 8313
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Number           2968 non-null   float64
 1   Name             8314 non-null   object
 2   Position         8314 non-null   object
 3   Date of Birth    8314 non-null   object
 4   Age              8310 non-null   object
 5   Nationality      8291 non-null   object
 6   Birth Country    8314 non-null   object
 7   Place of Birth   7864 non-null   object
 8   Height           6966 non-null   object
 9   Market Value     8314 non-null   object
 10  Other Positions  4963 non-null   object
 11  Nationality 1    8291 non-null   object
 12  Nationality 2    4618 non-null   object
 13  Position 2       4962 non-null   object
 14  Position 3       2647 non-null   object
dtypes: float64(1), object(14)
memory usage: 974.4+ KB

## Split the date of birth column

In [5]:
df_global['Date of Birth'][0].strip().split(", ")

['Sep 21', '1985']

In [6]:
df_global.head()

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value,Other Positions,Nationality 1,Nationality 2,Position 2,Position 3
0,16.0,Jean-Louis Leca,Goalkeeper,"Sep 21, 1985",38,France,France,Bastia,"1,80",€200k,NaN,France,NaN,NaN,NaN
1,NaN,Mathieu Suffissais,Goalkeeper,"May 30, 1985",38,France,France,Laval,"1,83",-,NaN,France,NaN,NaN,NaN
2,NaN,Gérald Delaporte,Goalkeeper,"Dec 18, 1985",38,France,France,NaN,NaN,-,NaN,France,NaN,NaN,NaN
3,NaN,Thomas Fedrigo,Goalkeeper,"May 10, 1985",38,"France, Italy",France,Paray-le-Monial,"1,80",-,NaN,France,Italy,NaN,NaN
4,NaN,Florian Piolot,Goalkeeper,"Dec 24, 1985",38,France,France,Pabu,"1,86",-,NaN,France,NaN,NaN,NaN

In [7]:
df_global[['Date', 'Year']] = df_global['Date of Birth'].str.strip().str.split(", ",expand=True)

In [8]:
df_global.head()

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value,Other Positions,Nationality 1,Nationality 2,Position 2,Position 3,Date,Year
0,16.0,Jean-Louis Leca,Goalkeeper,"Sep 21, 1985",38,France,France,Bastia,"1,80",€200k,NaN,France,NaN,NaN,NaN,Sep 21,1985
1,NaN,Mathieu Suffissais,Goalkeeper,"May 30, 1985",38,France,France,Laval,"1,83",-,NaN,France,NaN,NaN,NaN,May 30,1985
2,NaN,Gérald Delaporte,Goalkeeper,"Dec 18, 1985",38,France,France,NaN,NaN,-,NaN,France,NaN,NaN,NaN,Dec 18,1985
3,NaN,Thomas Fedrigo,Goalkeeper,"May 10, 1985",38,"France, Italy",France,Paray-le-Monial,"1,80",-,NaN,France,Italy,NaN,NaN,May 10,1985
4,NaN,Florian Piolot,Goalkeeper,"Dec 24, 1985",38,France,France,Pabu,"1,86",-,NaN,France,NaN,NaN,NaN,Dec 24,1985

## Group By

In [9]:
df_global.groupby("Year")["Name"].count()

Year
1985    255
1986    297
1987    289
1988    374
1989    375
1990    358
1991    397
1992    443
1993    387
1994    438
1995    431
1996    433
1997    430
1998    435
1999    477
2000    509
2001    486
2002    463
2003    375
2004    296
2005    310
Name: Name, dtype: int64