## Imports

In [1]:
import pandas as pd

In [2]:
df_global = pd.DataFrame

In [3]:
df_global = pd.read_csv("../../data/brazil/brazil_clean.csv")

In [4]:
df_global.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14697 entries, 0 to 14696
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Number           3199 non-null   float64
 1   Name             14697 non-null  object
 2   Position         14697 non-null  object
 3   Date of Birth    14697 non-null  object
 4   Age              14692 non-null  object
 5   Nationality      14668 non-null  object
 6   Birth Country    14697 non-null  object
 7   Place of Birth   10877 non-null  object
 8   Height           12539 non-null  object
 9   Market Value     14697 non-null  object
 10  Other Positions  7480 non-null   object
 11  Nationality 1    14668 non-null  object
 12  Nationality 2    1414 non-null   object
 13  Position 2       7480 non-null   object
 14  Position 3       3752 non-null   object
dtypes: float64(1), object(14)
memory usage: 1.7+ MB

## Split the date of birth column

In [5]:
df_global['Date of Birth'][0].strip().split(", ")

['Dec 12', '1985']

In [6]:
df_global.head()

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value,Other Positions,Nationality 1,Nationality 2,Position 2,Position 3
0,1.0,Guilherme,Goalkeeper,"Dec 12, 1985",38,"Russia, Brazil",Brazil,Cataguases,"1,97",€300k,NaN,Russia,Brazil,NaN,NaN
1,NaN,Diego Alves,Goalkeeper,"Jun 24, 1985",38,"Brazil, Italy",Brazil,Rio de Janeiro,"1,87",€150k,NaN,Brazil,Italy,NaN,NaN
2,1.0,Gerson Dida,Goalkeeper,"Aug 7, 1985",38,Brazil,Brazil,Sao Paulo,"1,90",-,NaN,Brazil,NaN,NaN,NaN
3,NaN,Carlão,Goalkeeper,"Dec 31, 1985",38,Brazil,Brazil,Bayeux,"1,90",-,NaN,Brazil,NaN,NaN,NaN
4,NaN,Evandro Gigante,Goalkeeper,"Nov 17, 1985",38,Brazil,Brazil,Belem,"1,93",-,NaN,Brazil,NaN,NaN,NaN

In [7]:
df_global[['Date', 'Year']] = df_global['Date of Birth'].str.strip().str.split(", ",expand=True)

In [8]:
df_global.head()

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value,Other Positions,Nationality 1,Nationality 2,Position 2,Position 3,Date,Year
0,1.0,Guilherme,Goalkeeper,"Dec 12, 1985",38,"Russia, Brazil",Brazil,Cataguases,"1,97",€300k,NaN,Russia,Brazil,NaN,NaN,Dec 12,1985
1,NaN,Diego Alves,Goalkeeper,"Jun 24, 1985",38,"Brazil, Italy",Brazil,Rio de Janeiro,"1,87",€150k,NaN,Brazil,Italy,NaN,NaN,Jun 24,1985
2,1.0,Gerson Dida,Goalkeeper,"Aug 7, 1985",38,Brazil,Brazil,Sao Paulo,"1,90",-,NaN,Brazil,NaN,NaN,NaN,Aug 7,1985
3,NaN,Carlão,Goalkeeper,"Dec 31, 1985",38,Brazil,Brazil,Bayeux,"1,90",-,NaN,Brazil,NaN,NaN,NaN,Dec 31,1985
4,NaN,Evandro Gigante,Goalkeeper,"Nov 17, 1985",38,Brazil,Brazil,Belem,"1,93",-,NaN,Brazil,NaN,NaN,NaN,Nov 17,1985

## Group By

In [9]:
df_global.groupby("Year")["Name"].count()

Year
1985    428
1986    500
1987    495
1988    611
1989    643
1990    652
1991    634
1992    735
1993    730
1994    787
1995    853
1996    854
1997    849
1998    867
1999    958
2000    954
2001    810
2002    770
2003    655
2004    509
2005    292
Name: Name, dtype: int64