## Imports

In [1]:
import pandas as pd

In [2]:
df_global = pd.DataFrame

In [3]:
df_global = pd.read_csv("../../data/england/england_clean.csv")

In [4]:
df_global.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9233 entries, 0 to 9232
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Number           3335 non-null   float64
 1   Name             9233 non-null   object
 2   Position         9233 non-null   object
 3   Date of Birth    9233 non-null   object
 4   Age              9233 non-null   object
 5   Nationality      9228 non-null   object
 6   Birth Country    9233 non-null   object
 7   Place of Birth   8871 non-null   object
 8   Height           7185 non-null   object
 9   Market Value     9233 non-null   object
 10  Main Position    8281 non-null   object
 11  Other Positions  5438 non-null   object
 12  Nationality 1    9228 non-null   object
 13  Nationality 2    2761 non-null   object
 14  Position 2       5438 non-null   object
 15  Position 3       2832 non-null   object
dtypes: float64(1), object(15)
memory usage: 1.1+ MB

## Split the date of birth column

In [5]:
df_global['Date of Birth'][0].strip().split(", ")

['Sep 3', '1985']

In [6]:
df_global.head()

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value,Main Position,Other Positions,Nationality 1,Nationality 2,Position 2,Position 3
0,33.0,Scott Carson,Goalkeeper,"Sep 3, 1985",38,England,England,Whitehaven,"1,88",€200k,NaN,NaN,England,NaN,NaN,NaN
1,NaN,Luke McShane,Goalkeeper,"Nov 6, 1985",38,England,England,Peterborough,"1,85",-,NaN,NaN,England,NaN,NaN,NaN
2,NaN,Jacob Giles,Goalkeeper,"Oct 12, 1985",38,England,England,Huddersfield,NaN,-,NaN,NaN,England,NaN,NaN,NaN
3,NaN,Greg Smith,Goalkeeper,"May 30, 1985",38,England,England,Stoke-on-Trent,NaN,-,NaN,NaN,England,NaN,NaN,NaN
4,NaN,Tim Deasy,Goalkeeper,"Oct 1, 1985",38,England,England,Salford,"1,85",-,NaN,NaN,England,NaN,NaN,NaN

In [7]:
df_global[['Date', 'Year']] = df_global['Date of Birth'].str.strip().str.split(", ",expand=True)

In [8]:
df_global.head()

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value,Main Position,Other Positions,Nationality 1,Nationality 2,Position 2,Position 3,Date,Year
0,33.0,Scott Carson,Goalkeeper,"Sep 3, 1985",38,England,England,Whitehaven,"1,88",€200k,NaN,NaN,England,NaN,NaN,NaN,Sep 3,1985
1,NaN,Luke McShane,Goalkeeper,"Nov 6, 1985",38,England,England,Peterborough,"1,85",-,NaN,NaN,England,NaN,NaN,NaN,Nov 6,1985
2,NaN,Jacob Giles,Goalkeeper,"Oct 12, 1985",38,England,England,Huddersfield,NaN,-,NaN,NaN,England,NaN,NaN,NaN,Oct 12,1985
3,NaN,Greg Smith,Goalkeeper,"May 30, 1985",38,England,England,Stoke-on-Trent,NaN,-,NaN,NaN,England,NaN,NaN,NaN,May 30,1985
4,NaN,Tim Deasy,Goalkeeper,"Oct 1, 1985",38,England,England,Salford,"1,85",-,NaN,NaN,England,NaN,NaN,NaN,Oct 1,1985

## Group By

In [9]:
df_global.groupby("Year")["Name"].count()

Year
1985    259
1986    323
1987    336
1988    362
1989    389
1990    391
1991    472
1992    445
1993    524
1994    512
1995    517
1996    527
1997    569
1998    491
1999    548
2000    529
2001    527
2002    481
2003    419
2004    361
2005    231
Name: Name, dtype: int64