## Imports

In [1]:
import pandas as pd

In [2]:
df_global = pd.DataFrame

In [3]:
df_global = pd.read_csv("../../data/portugal/portugal_clean.csv")

In [4]:
df_global.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6630 entries, 0 to 6629
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Number           3682 non-null   float64
 1   Name             6630 non-null   object
 2   Position         6630 non-null   object
 3   Date of Birth    6630 non-null   object
 4   Age              6629 non-null   object
 5   Nationality      6624 non-null   object
 6   Birth Country    6630 non-null   object
 7   Place of Birth   5763 non-null   object
 8   Height           5011 non-null   object
 9   Market Value     6501 non-null   object
 10  Main Position    5822 non-null   object
 11  Other Positions  3986 non-null   object
 12  Nationality 1    6624 non-null   object
 13  Nationality 2    644 non-null    object
 14  Position 2       3985 non-null   object
 15  Position 3       1794 non-null   object
dtypes: float64(1), object(15)
memory usage: 828.9+ KB

## Split the date of birth column

In [5]:
df_global['Date of Birth'][0].strip().split(", ")

['Apr 14', '1985']

In [6]:
df_global.head()

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value,Main Position,Other Positions,Nationality 1,Nationality 2,Position 2,Position 3
0,1.0,António Filipe,Goalkeeper,"Apr 14, 1985",38,Portugal,Portugal,Gondomar,NaN,"1,87",NaN,NaN,Portugal,NaN,NaN,NaN
1,NaN,Carlos Magalhães,Goalkeeper,"Apr 15, 1985",38,Portugal,Portugal,Porto,NaN,"1,78",NaN,NaN,Portugal,NaN,NaN,NaN
2,NaN,Manuel Silveira,Goalkeeper,"May 28, 1985",38,"Portugal, Andorra",Portugal,NaN,NaN,NaN,NaN,NaN,Portugal,Andorra,NaN,NaN
3,NaN,Tiago Alves,Goalkeeper,"May 15, 1985",38,"Portugal, France",Portugal,Chaves,NaN,"1,83",NaN,NaN,Portugal,France,NaN,NaN
4,NaN,Torcato,Goalkeeper,"Feb 15, 1985",39,Portugal,Portugal,Penafiel,NaN,"1,80",NaN,NaN,Portugal,NaN,NaN,NaN

In [7]:
df_global[['Date', 'Year']] = df_global['Date of Birth'].str.strip().str.split(", ",expand=True)

In [8]:
df_global.head()

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value,Main Position,Other Positions,Nationality 1,Nationality 2,Position 2,Position 3,Date,Year
0,1.0,António Filipe,Goalkeeper,"Apr 14, 1985",38,Portugal,Portugal,Gondomar,NaN,"1,87",NaN,NaN,Portugal,NaN,NaN,NaN,Apr 14,1985
1,NaN,Carlos Magalhães,Goalkeeper,"Apr 15, 1985",38,Portugal,Portugal,Porto,NaN,"1,78",NaN,NaN,Portugal,NaN,NaN,NaN,Apr 15,1985
2,NaN,Manuel Silveira,Goalkeeper,"May 28, 1985",38,"Portugal, Andorra",Portugal,NaN,NaN,NaN,NaN,NaN,Portugal,Andorra,NaN,NaN,May 28,1985
3,NaN,Tiago Alves,Goalkeeper,"May 15, 1985",38,"Portugal, France",Portugal,Chaves,NaN,"1,83",NaN,NaN,Portugal,France,NaN,NaN,May 15,1985
4,NaN,Torcato,Goalkeeper,"Feb 15, 1985",39,Portugal,Portugal,Penafiel,NaN,"1,80",NaN,NaN,Portugal,NaN,NaN,NaN,Feb 15,1985

## Group By

In [9]:
df_global.groupby("Year")["Name"].count()

Year
1985    177
1986    193
1987    196
1988    224
1989    216
1990    247
1991    250
1992    276
1993    295
1994    335
1995    331
1996    353
1997    323
1998    447
1999    485
2000    488
2001    429
2002    393
2003    419
2004    306
2005    226
Name: Name, dtype: int64