## Imports

In [14]:
import pandas as pd

In [15]:
df_global = pd.DataFrame

In [16]:
df_global = pd.read_csv("../../data/argentina/argentina_clean.csv")

In [17]:
df_global.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6977 entries, 0 to 6976
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Number           2091 non-null   float64
 1   Name             6977 non-null   object
 2   Position         6977 non-null   object
 3   Date of Birth    6977 non-null   object
 4   Age              6976 non-null   object
 5   Nationality      6975 non-null   object
 6   Birth Country    6977 non-null   object
 7   Place of Birth   5928 non-null   object
 8   Height           6205 non-null   object
 9   Market Value     6977 non-null   object
 10  Other Positions  3131 non-null   object
 11  Nationality 1    6975 non-null   object
 12  Nationality 2    1882 non-null   object
 13  Position 2       3130 non-null   object
 14  Position 3       1514 non-null   object
dtypes: float64(1), object(14)
memory usage: 817.7+ KB

## Split the date of birth column

In [19]:
df_global['Date of Birth'][0].strip().split(", ")

['Nov 13', '1985']

In [20]:
df_global.head()

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value,Other Positions,Nationality 1,Nationality 2,Position 2,Position 3
0,1.0,Cristian Álvarez,Goalkeeper,"Nov 13, 1985",38,"Argentina, Spain",Argentina,Rosario,"1,86",€100k,NaN,Argentina,Spain,NaN,NaN
1,NaN,Nereo Champagne,Goalkeeper,"Jan 20, 1985",39,"Argentina, Italy",Argentina,Salto,"1,88",€10k,NaN,Argentina,Italy,NaN,NaN
2,1.0,Rodrigo Pombo,Goalkeeper,"Jun 16, 1985",38,Argentina,Argentina,Cordoba,NaN,-,NaN,Argentina,NaN,NaN,NaN
3,NaN,Gastón Folgar,Goalkeeper,"Mar 7, 1985",39,Argentina,Argentina,Buenos Aires,NaN,-,NaN,Argentina,NaN,NaN,NaN
4,NaN,Ángel Pedroso,Goalkeeper,"Jun 18, 1985",38,Argentina,Argentina,Formosa,NaN,-,NaN,Argentina,NaN,NaN,NaN

In [27]:
df_global[['Date', 'Year']] = df_global['Date of Birth'].str.strip().str.split(", ",expand=True)

In [11]:
df_global.head()

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value,Other Positions,Nationality 1,Nationality 2,Position 2,Position 3,Date,Year
0,1.0,Cristian Álvarez,Goalkeeper,"Nov 13, 1985",38,"Argentina, Spain",Argentina,Rosario,"1,86",€100k,NaN,Argentina,Spain,NaN,NaN,Nov 13,1985
1,NaN,Nereo Champagne,Goalkeeper,"Jan 20, 1985",39,"Argentina, Italy",Argentina,Salto,"1,88",€10k,NaN,Argentina,Italy,NaN,NaN,Jan 20,1985
2,1.0,Rodrigo Pombo,Goalkeeper,"Jun 16, 1985",38,Argentina,Argentina,Cordoba,NaN,-,NaN,Argentina,NaN,NaN,NaN,Jun 16,1985
3,NaN,Gastón Folgar,Goalkeeper,"Mar 7, 1985",39,Argentina,Argentina,Buenos Aires,NaN,-,NaN,Argentina,NaN,NaN,NaN,Mar 7,1985
4,NaN,Ángel Pedroso,Goalkeeper,"Jun 18, 1985",38,Argentina,Argentina,Formosa,NaN,-,NaN,Argentina,NaN,NaN,NaN,Jun 18,1985

## Group By

In [28]:
df_global.groupby("Year")["Name"].count()

Year
1985    271
1986    272
1987    300
1988    322
1989    292
1990    328
1991    297
1992    332
1993    354
1994    315
1995    419
1996    406
1997    427
1998    461
1999    462
2000    476
2001    416
2002    328
2003    263
2004    162
2005     59
Name: Name, dtype: int64