## Imports

In [1]:
import pandas as pd

In [2]:
df_global = pd.DataFrame

In [3]:
df_global = pd.read_csv("../../data/spain/spain_clean.csv")

In [4]:
df_global.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12395 entries, 0 to 12394
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Number           4558 non-null   float64
 1   Name             12395 non-null  object
 2   Position         12395 non-null  object
 3   Date of Birth    12395 non-null  object
 4   Age              12392 non-null  object
 5   Nationality      12375 non-null  object
 6   Birth Country    12395 non-null  object
 7   Place of Birth   12067 non-null  object
 8   Height           7336 non-null   object
 9   Market Value     11826 non-null  object
 10  Main Position    10831 non-null  object
 11  Other Positions  5333 non-null   object
 12  Nationality 1    12375 non-null  object
 13  Nationality 2    813 non-null    object
 14  Nationality 3    1 non-null      object
 15  Position 2       5332 non-null   object
 16  Position 3       2104 non-null   object
dtypes: float64(1), object(16)
memory usage: 1.6+ MB

## Split the date of birth column

In [5]:
df_global['Date of Birth'][0].strip().split(", ")

['Dec 2', '1985']

In [6]:
df_global.head()

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value,Main Position,Other Positions,Nationality 1,Nationality 2,Nationality 3,Position 2,Position 3
0,1.0,Biel Ribas,Goalkeeper,"Dec 2, 1985",38,Spain,Spain,Palma de Mallorca,NaN,"1,86",NaN,NaN,Spain,NaN,NaN,NaN,NaN
1,13.0,Roberto Santamaría,Goalkeeper,"Feb 27, 1985",39,Spain,Spain,Pamplona,NaN,"1,83",NaN,NaN,Spain,NaN,NaN,NaN,NaN
2,NaN,Miguel Ángel Ávila,Goalkeeper,"Apr 18, 1985",39,Spain,Spain,Torremolinos,NaN,"1,82",NaN,NaN,Spain,NaN,NaN,NaN,NaN
3,NaN,Francisco Javier Rosales Simón,Goalkeeper,"Dec 9, 1985",38,Spain,Spain,La Linea de la Conceocion,NaN,"1,80",NaN,NaN,Spain,NaN,NaN,NaN,NaN
4,NaN,Francisco Asta,Goalkeeper,"Nov 4, 1985",38,Spain,Spain,Almeria,NaN,"1,83",NaN,NaN,Spain,NaN,NaN,NaN,NaN

In [7]:
df_global[['Date', 'Year']] = df_global['Date of Birth'].str.strip().str.split(", ",expand=True)

In [8]:
df_global.head()

,Number,Name,Position,Date of Birth,Age,Nationality,Birth Country,Place of Birth,Height,Market Value,Main Position,Other Positions,Nationality 1,Nationality 2,Nationality 3,Position 2,Position 3,Date,Year
0,1.0,Biel Ribas,Goalkeeper,"Dec 2, 1985",38,Spain,Spain,Palma de Mallorca,NaN,"1,86",NaN,NaN,Spain,NaN,NaN,NaN,NaN,Dec 2,1985
1,13.0,Roberto Santamaría,Goalkeeper,"Feb 27, 1985",39,Spain,Spain,Pamplona,NaN,"1,83",NaN,NaN,Spain,NaN,NaN,NaN,NaN,Feb 27,1985
2,NaN,Miguel Ángel Ávila,Goalkeeper,"Apr 18, 1985",39,Spain,Spain,Torremolinos,NaN,"1,82",NaN,NaN,Spain,NaN,NaN,NaN,NaN,Apr 18,1985
3,NaN,Francisco Javier Rosales Simón,Goalkeeper,"Dec 9, 1985",38,Spain,Spain,La Linea de la Conceocion,NaN,"1,80",NaN,NaN,Spain,NaN,NaN,NaN,NaN,Dec 9,1985
4,NaN,Francisco Asta,Goalkeeper,"Nov 4, 1985",38,Spain,Spain,Almeria,NaN,"1,83",NaN,NaN,Spain,NaN,NaN,NaN,NaN,Nov 4,1985

## Group By

In [9]:
df_global.groupby("Year")["Name"].count()

Year
1985    373
1986    396
1987    445
1988    465
1989    514
1990    550
1991    488
1992    553
1993    620
1994    584
1995    705
1996    631
1997    716
1998    667
1999    726
2000    827
2001    796
2002    693
2003    669
2004    558
2005    372
Name: Name, dtype: int64